name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to server
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SEARCHAPI_KEY: ${{ secrets.SEARCHAPI_KEY }}
        secret: ${{ secrets.SESSION_SECRET }}
      run: |
        echo "Deploying to Railway with environment variables..."
        
    - name: Deploy to Railway
      uses: bervProject/railway-deploy@v1.0.0
      with:
        service: ${{ secrets.RAILWAY_SERVICE }}
        token: ${{ secrets.RAILWAY_TOKEN }}
